# Generated by Django 4.2.16 on 2025-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
