# Generated by Django 4.2.16 on 2024-12-15 19:16

import adjango.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oto_user',
            field=adjango.fields.AOneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordersoto', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=adjango.fields.AForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
